development: &default
  adapter: postgresql
  host: db
  encoding: utf8
  database: hr_dash_dev
  pool: 5
  username: postgres
  password: postgres

test:
  <<: *default
  database: hr_dash_test

production:
  <<: *default
  database: hr_dash_production
  username: <%= ENV["HR_DASH_DB_USERNAME"] %>
  password: <%= ENV["HR_DASH_DB_PASSWORD"] %>
